version: '2.12.0'
services:
  db:
    container_name: db
    image: mongo:latest
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"

  web-app:
    container_name: web-app
    build: ./web-app
    ports:
      - "4001:4001"
    depends_on:
      - db
    environment:
      MONGO_DBNAME: ratemyapartment 
      MONGO_URI: mongodb+srv://admin:team4FINALPROJECT@ratemyapartment.y9m9ut3.mongodb.net/test
      
  